/* educatifs-data.js — Banque complète d'éducatifs par moyen d'action PFEQ */

const MOYENS_ACTION = {
  manipulation_balles: {
    label: "Manipulation — Objets portés",
    icon: "🏀", color: "#004EBF",
    subtitle: "Balles, ballons, poches de fèves, objets à lancer/attraper",
    cycles: ["Préscolaire","1er cycle","2e cycle","3e cycle"],
  },
  manipulation_engins: {
    label: "Manipulation — Objets propulsés",
    icon: "🏸", color: "#8e44ad",
    subtitle: "Raquettes, bâtons de hockey, crosses, bâtons de ringuette",
    cycles: ["1er cycle","2e cycle","3e cycle"],
  },
  locomotion: {
    label: "Locomotion",
    icon: "🏃", color: "#c0392b",
    subtitle: "Course, saut, galop, saut à la corde, glissade",
    cycles: ["Préscolaire","1er cycle","2e cycle","3e cycle"],
  },
  stabilisation: {
    label: "Stabilisation / Mobilité",
    icon: "🤸", color: "#1a7f3c",
    subtitle: "Équilibre, rotation, renversement, acrobatie douce",
    cycles: ["Préscolaire","1er cycle","2e cycle","3e cycle"],
  },
  cooperation: {
    label: "Coopération",
    icon: "🤝", color: "#e67e22",
    subtitle: "Jeux collectifs, travail en équipe, défis communs",
    cycles: ["Préscolaire","1er cycle","2e cycle","3e cycle"],
  },
  opposition: {
    label: "Opposition",
    icon: "⚔️", color: "#7b1fa2",
    subtitle: "Ballon chasseur, duels, jeux d'opposition",
    cycles: ["1er cycle","2e cycle","3e cycle"],
  },
  expression: {
    label: "Expression / Danse",
    icon: "💃", color: "#ad1457",
    subtitle: "Danse créative, expression dramatique, rythme corporel",
    cycles: ["Préscolaire","1er cycle","2e cycle","3e cycle"],
  },
  plein_air: {
    label: "Plein air / Nature",
    icon: "🌿", color: "#00796b",
    subtitle: "Activités en nature, orientation, patin, ski adapté",
    cycles: ["1er cycle","2e cycle","3e cycle"],
  },
};

const OBJECTIFS_PFEQ = {
  manipulation_balles: {
    "Préscolaire": [
      "Explorer différentes façons de lancer et d'attraper une balle",
      "Découvrir des balles de formes, tailles et textures variées",
      "Développer la coordination œil-main de base",
      "Participer avec plaisir à des activités de manipulation",
    ],
    "1er cycle": [
      "Lancer une balle avec précision sur une cible à courte distance",
      "Attraper une balle lancée à deux mains avec contrôle",
      "Rouler une balle avec précision vers une cible",
      "Botter une balle en direction d'une cible",
      "Démontrer une progression dans la maîtrise des habiletés de manipulation",
    ],
    "2e cycle": [
      "Lancer une balle avec précision à moyenne et longue distance",
      "Attraper une balle à une main et en déplacement",
      "Effectuer des passes à un partenaire avec contrôle",
      "Combiner des habiletés de manipulation dans des situations de jeu",
      "Adapter son niveau de force selon la situation",
    ],
    "3e cycle": [
      "Maîtriser plusieurs types de lancers (par-dessus, par-dessous, en rotation)",
      "Effectuer des habiletés de manipulation sous pression défensive",
      "Utiliser des stratégies offensives et défensives en jeu",
      "Évaluer ses propres performances et proposer des ajustements",
      "Démontrer une maîtrise technique dans des situations complexes",
    ],
  },
  locomotion: {
    "Préscolaire": [
      "Explorer différents modes de déplacement (marche, course, saut, ramper)",
      "Sauter sur deux pieds et atterrir de façon contrôlée",
      "Galoper, sautiller et faire des pas chassés",
      "Se déplacer en suivant un tracé simple",
    ],
    "1er cycle": [
      "Courir à différentes vitesses avec contrôle",
      "Sauter en longueur et en hauteur avec élan",
      "Sauter à la corde individuel (5+ sauts consécutifs)",
      "Effectuer un relais simple avec transmission de témoin",
      "Adapte sa vitesse selon la situation (sprint/endurance)",
    ],
    "2e cycle": [
      "Courir avec efficacité sur des distances variées",
      "Sauter à la corde individuel avec variantes",
      "Effectuer des sauts combinés (course + saut en longueur)",
      "Démontrer une bonne technique de course (bras, posture)",
      "Participer à des relais avec stratégie d'équipe",
    ],
    "3e cycle": [
      "Démontrer une technique de course efficace en sprints et en endurance",
      "Réaliser des sauts avec précision et puissance",
      "Sauter à la corde avec variantes avancées",
      "Appliquer des stratégies lors de relais en équipe",
      "Évaluer ses performances en locomotion et se fixer des défis",
    ],
  },
  stabilisation: {
    "Préscolaire": [
      "Maintenir l'équilibre sur un pied quelques secondes",
      "Effectuer des roulades avant simples sur tapis",
      "Se déplacer sur des surfaces instables (poutres basses)",
      "Explorer des positions inversées (pieds en l'air avec aide)",
    ],
    "1er cycle": [
      "Maintenir l'équilibre sur un pied 5+ secondes",
      "Effectuer une roulade avant et arrière contrôlée",
      "Marcher sur une poutre d'équilibre basse",
      "Réaliser des postures de yoga simples",
      "Combiner deux éléments de stabilisation",
    ],
    "2e cycle": [
      "Maîtriser des postures d'équilibre variées sur surfaces stables et instables",
      "Effectuer des roulades combinées (avant + arrière)",
      "Réaliser des pyramides humaines simples à 2-3 personnes",
      "Démontrer un renversement contrôlé (appui facial)",
      "Enchaîner 3+ éléments de stabilisation",
    ],
    "3e cycle": [
      "Réaliser des enchaînements acrobatiques à 3+ éléments",
      "Construire et présenter des pyramides humaines à 3+ personnes",
      "Démontrer des appuis renversés avec qualité technique",
      "Chorégraphier une séquence acrobatique en groupe",
      "Évaluer et améliorer la qualité de ses enchaînements",
    ],
  },
  cooperation: {
    "Préscolaire": [
      "Participer à des jeux en équipe avec plaisir",
      "Aider un camarade dans une tâche physique",
      "Respecter les règles simples d'un jeu coopératif",
      "Communiquer avec ses coéquipiers de façon positive",
    ],
    "1er cycle": [
      "Contribuer activement au succès de son équipe",
      "Communiquer efficacement pour accomplir une tâche collective",
      "Respecter les règles et les rôles dans un jeu coopératif",
      "Résoudre un défi physique en équipe",
      "Encourager ses coéquipiers",
    ],
    "2e cycle": [
      "Assumer différents rôles dans une équipe (leader, suiveur, observateur)",
      "Proposer des stratégies pour améliorer la performance collective",
      "Gérer positivement les conflits lors d'activités d'équipe",
      "Adapter son comportement selon les besoins de l'équipe",
      "Démontrer de la solidarité envers tous les membres de l'équipe",
    ],
    "3e cycle": [
      "Exercer un leadership positif au sein de l'équipe",
      "Élaborer et appliquer des stratégies collectives efficaces",
      "Évaluer la dynamique de son équipe et proposer des améliorations",
      "Intégrer des joueurs de tous les niveaux dans la stratégie",
      "Faire preuve de fairplay en toutes circonstances",
    ],
  },
  opposition: {
    "1er cycle": [
      "Participer à des jeux d'opposition simples avec fair-play",
      "Comprendre les règles de base du ballon chasseur",
      "Développer des stratégies défensives élémentaires (esquiver)",
      "Respecter les décisions de l'arbitre",
    ],
    "2e cycle": [
      "Utiliser des stratégies offensives variées (lancer, feinte)",
      "Développer des stratégies défensives (esquive, blocage, capture)",
      "Coordonner ses actions avec celles des coéquipiers",
      "Appliquer les règles du jeu de façon autonome",
      "Évaluer les stratégies utilisées et proposer des ajustements",
    ],
    "3e cycle": [
      "Maîtriser un répertoire varié de stratégies offensives et défensives",
      "Analyser les stratégies adverses et s'y adapter",
      "Organiser la défense et l'attaque de son équipe",
      "Arbitrer un jeu d'opposition avec justesse",
      "Évaluer ses performances tactiques et techniques",
    ],
  },
  expression: {
    "Préscolaire": [
      "Explorer le mouvement expressif librement",
      "Bouger en suivant un rythme simple",
      "Imiter des personnages, animaux ou éléments de la nature",
      "Participer avec plaisir à des activités de danse",
    ],
    "1er cycle": [
      "Reproduire des séquences de mouvements simples",
      "S'exprimer corporellement sur différents types de musique",
      "Créer un mini-enchaînement de 4+ mouvements",
      "Découvrir des danses de cultures du monde",
      "Bouger en synchronie avec un partenaire",
    ],
    "2e cycle": [
      "Créer et présenter une chorégraphie en groupe (8+ mouvements)",
      "Utiliser différentes qualités de mouvement (lent/vif, fort/doux)",
      "Interpréter une danse culturelle avec aisance",
      "Utiliser l'espace de façon créative dans ses créations",
      "Apprécier les productions des autres de façon constructive",
    ],
    "3e cycle": [
      "Créer une chorégraphie originale intégrant des éléments culturels",
      "Maîtriser les éléments fondamentaux du mouvement dansé",
      "Présenter une performance avec qualité artistique",
      "Utiliser la notation chorégraphique simple",
      "Diriger la création chorégraphique d'un groupe",
    ],
  },
  manipulation_engins: {
    "1er cycle": [
      "Tenir correctement une raquette / un bâton",
      "Frapper un objet statique avec un engin",
      "Contrôler un ballon/rondelle avec un bâton à courte distance",
      "Participer à des échanges simples avec raquette",
    ],
    "2e cycle": [
      "Frapper un objet en mouvement avec précision",
      "Effectuer des passes à un partenaire avec engin",
      "Contrôler la force et la direction des frappes",
      "Participer à des jeux simples avec engin (mini-hockey, badminton)",
    ],
    "3e cycle": [
      "Maîtriser plusieurs types de frappes (coup droit, revers, smash)",
      "Appliquer des stratégies de jeu avec engin",
      "Combiner déplacement et manipulation avec engin",
      "Évaluer sa technique et s'auto-corriger",
      "Arbitrer un jeu avec engin",
    ],
  },
  plein_air: {
    "1er cycle": [
      "Se déplacer en toute sécurité dans un environnement extérieur",
      "Identifier les règles de sécurité en plein air",
      "Participer à des jeux et activités en nature",
      "Respecter l'environnement naturel",
    ],
    "2e cycle": [
      "Utiliser une boussole et une carte simples",
      "Planifier un itinéraire simple en plein air",
      "Démontrer des habiletés motrices adaptées au plein air",
      "Appliquer les règles de sécurité de façon autonome",
      "Coopérer avec son équipe lors d'activités en plein air",
    ],
    "3e cycle": [
      "Maîtriser les habiletés de déplacement propres à l'activité de plein air choisie",
      "Planifier et réaliser une sortie en plein air en autonomie",
      "Appliquer des stratégies de survie/orientation de base",
      "Respecter et valoriser l'environnement naturel",
      "Évaluer les risques et adapter son comportement",
    ],
  },
};

const EDUCATIFS = {
  manipulation_balles: [
    {
      id:"MB_E1", categorie:"echauffement", nom:"🔥 La Balle Chaude",
      durees:[5,7,8], cycles:["Préscolaire","1er cycle","2e cycle","3e cycle"],
      materiel:["1 balle par groupe de 6-8 élèves"],
      description:"Les élèves en cercle se passent la balle le plus rapidement possible. Si la balle tombe, tout le groupe fait 3 sauts sur place.",
      etapes:["Former des cercles de 6-8 élèves","Passer la balle dans un sens puis l'autre","Accélérer progressivement","Variante: 2 balles simultanément"],
      variantes:["Passer en diagonale","Passe au-dessus de la tête","Passe au sol (rouler)"],
    },
    {
      id:"MB_E2", categorie:"echauffement", nom:"🔥 Exploration Libre",
      durees:[5,8,10], cycles:["Préscolaire","1er cycle"],
      materiel:["1 balle par élève (variées: mousse, tennis, caoutchouc)"],
      description:"Chaque élève explore librement ce qu'il peut faire avec sa balle dans l'espace du gymnase. L'enseignant pose des défis: 'Peux-tu faire rebondir la balle 5 fois?'",
      etapes:["Distribuer une balle à chaque élève","Laisser explorer 2 min librement","Poser des défis progressifs","Partager les découvertes"],
      variantes:["Avec les deux mains","Avec la main non-dominante","En se déplaçant"],
    },
    {
      id:"MB_E3", categorie:"echauffement", nom:"🔥 Jongle 1 Balle",
      durees:[5,7], cycles:["1er cycle","2e cycle"],
      materiel:["1 balle par élève"],
      description:"Initiation au jonglage avec une balle: lancer légèrement en l'air et rattraper. Progresser vers des lancers plus hauts.",
      etapes:["Lancer et rattraper à deux mains","Lancer d'une main, attraper de l'autre","Lancer et applaudir avant d'attraper","Lancer et faire un tour sur soi"],
      variantes:["Yeux fermés","Assis par terre","En marchant"],
    },
    {
      id:"MB_P1", categorie:"principal", nom:"⭐ Lancer-Attraper Duo",
      durees:[8,10,12,15], cycles:["Préscolaire","1er cycle","2e cycle","3e cycle"],
      materiel:["1 balle pour 2 élèves","Cônes pour délimiter les distances"],
      description:"En paires, les élèves s'exercent à lancer et attraper. L'enseignant guide la progression des distances et des types de lancers.",
      etapes:["Placer les paires face à face (3m)","Lancer-attraper à 2 mains (10 échanges)","Reculer de 2m et recommencer","Introduire lancer à 1 main","Introduire des pas avant le lancer"],
      variantes:["Lancer par-dessous","Lancer par-dessus","Lancer en rotation","Attraper à 1 main"],
    },
    {
      id:"MB_P2", categorie:"principal", nom:"⭐ La Cible",
      durees:[10,12,15], cycles:["1er cycle","2e cycle","3e cycle"],
      materiel:["3-4 balles par station","Cerceaux ou cibles au mur","Cônes"],
      description:"Stations de lancer vers des cibles variées (cerceaux au mur, quilles à renverser, paniers). Points selon la difficulté.",
      etapes:["Installer 4-6 stations de lancer","2-3 élèves par station (3 min)","Rotation après le signal","Comptabiliser les points","Défi final: meilleure station"],
      variantes:["Cibles mobiles (balançoires de cônes)","Distance augmentée","Lancer non-dominant"],
    },
    {
      id:"MB_P3", categorie:"principal", nom:"⭐ Balle au Mur",
      durees:[8,10,12], cycles:["1er cycle","2e cycle","3e cycle"],
      materiel:["1 balle par élève ou par paire","Mur dégagé"],
      description:"Les élèves lancent la balle contre le mur et la rattrapent au rebond. Défis progressifs de distance et de complexité.",
      etapes:["Lancer à 1m du mur, attraper","Reculer à 2m, 3m progressivement","Lancer + rebond au sol avant d'attraper","Lancer + tour complet + attraper","En paire: lancer en alternance"],
      variantes:["Lancer au-dessus d'une ligne","Attraper sur rebond multiple","Ajouter une squatdown avant d'attraper"],
    },
    {
      id:"MB_P4", categorie:"principal", nom:"⭐ Circuit de Stations",
      durees:[15,18,20], cycles:["2e cycle","3e cycle"],
      materiel:["Balles variées","4-6 stations équipées","Chronomètre","Fiches de station"],
      description:"Circuit de 4-6 stations travaillant différentes habiletés de manipulation. 3 minutes par station, rotation au signal.",
      etapes:["Présenter les 4-6 stations (2 min)","Répartir les élèves aux stations","Travailler 3 min par station","Rotation au signal sonore","Bilan après le circuit"],
      variantes:["Station 1: lancer précision","Station 2: jonglage","Station 3: attraper en mouvement","Station 4: balle au mur","Station 5: passes en groupe","Station 6: défi créatif"],
    },
    {
      id:"MB_P5", categorie:"principal", nom:"⭐ La Passe Enchaînée",
      durees:[8,10,12], cycles:["2e cycle","3e cycle"],
      materiel:["1 balle pour 5-6 élèves"],
      description:"En groupes, les élèves font circuler la balle selon un schéma de passes (numérotés ou avec schéma). Défis de vitesse.",
      etapes:["Former des groupes de 5-6","Attribuer un numéro à chacun","Passer toujours au même numéro (1→3→5→2→4→1)","Chronométrer 10 allers-retours","Défi: battre leur record"],
      variantes:["Deux balles simultanées","Passer en sens inverse","Passer + se déplacer vers la position du receveur"],
    },
    {
      id:"MB_J1", categorie:"jeu", nom:"🎮 Ballon Chasseur",
      durees:[10,12,15,18], cycles:["1er cycle","2e cycle","3e cycle"],
      materiel:["4-6 ballons de mousse","Cônes pour délimiter"],
      description:"Jeu classique d'opposition: deux équipes s'affrontent en cherchant à toucher les adversaires avec le ballon.",
      etapes:["Diviser en 2 équipes","Explication des règles (5 min)","Jeu (8-10 min)","Débriefing stratégique"],
      variantes:["Version prison","Version médicale (médecin secret)","Version 3 équipes","Sans ligne centrale (terrain libre)"],
    },
    {
      id:"MB_J2", categorie:"jeu", nom:"🎮 Zone de Tir",
      durees:[12,15,18], cycles:["2e cycle","3e cycle"],
      materiel:["Ballons","Cerceaux-cibles","Dossards 2 couleurs"],
      description:"Deux équipes s'affrontent: marquer des points en lançant des balles dans les cerceaux de l'adversaire tout en défendant les siens.",
      etapes:["Placer 4 cerceaux de chaque côté","Expliquer le système de points","Jeu 2×5 min","Pause stratégique","2e période"],
      variantes:["Cerceaux suspendus","Gardien de but possible","Zones de tir obligatoires"],
    },
    {
      id:"MB_J3", categorie:"jeu", nom:"🎮 10 Passes",
      durees:[10,12,15], cycles:["2e cycle","3e cycle"],
      materiel:["1 ballon par groupe de 8-10","Dossards 2 couleurs"],
      description:"Faire circuler le ballon dans son équipe pour atteindre 10 passes consécutives sans interception.",
      etapes:["2 équipes mélangées dans l'espace","Passes uniquement, pas de course avec le ballon","10 passes = 1 point","L'adversaire essaie d'intercepter"],
      variantes:["Maximum 3 secondes avec le ballon","Obligation de passer à un joueur non adjacent","2 touches minimum avant de passer"],
    },
    {
      id:"MB_R1", categorie:"retour", nom:"🧘 Étirements des Bras",
      durees:[3,5], cycles:["Préscolaire","1er cycle","2e cycle","3e cycle"],
      materiel:[],
      description:"Étirements doux des muscles des bras, épaules et poignets utilisés lors de la séance.",
      etapes:["Étirer les bras en croix (15s)","Ramener le coude devant soi (15s chaque bras)","Tourner les poignets en cercles","Doigts entrelacés, pousser vers l'extérieur","Respiration profonde × 3"],
      variantes:["Avec musique douce","En position assise ou debout","Guidé par un élève volontaire"],
    },
    {
      id:"MB_R2", categorie:"retour", nom:"🧘 Cercle de Discussion",
      durees:[5,7,8], cycles:["Préscolaire","1er cycle","2e cycle","3e cycle"],
      materiel:[],
      description:"Rassemblement en cercle pour réfléchir sur la séance: ce qui a bien fonctionné, les défis rencontrés, les apprentissages.",
      etapes:["S'asseoir en cercle","Partager: 'Qu'est-ce que j'ai appris aujourd'hui?'","Partager: 'Qu'est-ce qui était difficile?'","Fixer un défi pour la prochaine fois","Clôturer avec un applaudissement collectif"],
      variantes:["Tour de parole avec objet parlant","Écrire dans un journal sportif","Pouce en l'air/pouce en bas pour auto-évaluation"],
    },
  ],

  locomotion: [
    {
      id:"LOC_E1", categorie:"echauffement", nom:"🔥 Tour du Gymnase Progressif",
      durees:[5,7,8], cycles:["Préscolaire","1er cycle","2e cycle","3e cycle"],
      materiel:["Cônes pour délimiter"],
      description:"Les élèves font le tour du gymnase en augmentant progressivement l'intensité: marche → jogging → course → sprint (droites).",
      etapes:["Marche normale (1 tour)","Jogging léger (1 tour)","Course modérée (1 tour)","Sprint sur les droites, récup sur les courbes (2 tours)","Retour au jogging (1 tour)"],
      variantes:["Avec changements de direction au signal","Variantes de déplacement (saut, galop, chassé)","En file indienne par groupes"],
    },
    {
      id:"LOC_E2", categorie:"echauffement", nom:"🔥 Simon Dit Bouge!",
      durees:[5,7], cycles:["Préscolaire","1er cycle"],
      materiel:[],
      description:"Version sportive de Simon dit: les commandes sont des mouvements locomoteurs. Élève qui se trompe fait 3 sauts sur place.",
      etapes:["Expliquer les règles","Commencer lentement (marche, stop, sauter)","Accélérer le rythme","Ajouter des combinaisons (galop + tourner)","Élimination douce possible"],
      variantes:["Élève animateur","Commandes en anglais (immersion)","Thème: animaux (courir comme un cheval, sauter comme un kangourou)"],
    },
    {
      id:"LOC_E3", categorie:"echauffement", nom:"🔥 Échauffement Articulaire + Course",
      durees:[5,8], cycles:["2e cycle","3e cycle"],
      materiel:[],
      description:"Mobilisation articulaire complète suivie d'une activation cardiovasculaire progressive.",
      etapes:["Tourner les chevilles (10× chaque pied)","Rotations des genoux","Rotations des hanches","Tourner les épaules","Tourner le cou doucement","Jogging + accélérations progressives (5 min)"],
      variantes:["Guidé par un élève","Avec musique","Inclure des exercices spécifiques (talons-fesses, genoux-poitrine)"],
    },
    {
      id:"LOC_P1", categorie:"principal", nom:"⭐ Parcours de Sauts",
      durees:[10,12,15], cycles:["Préscolaire","1er cycle","2e cycle"],
      materiel:["Cerceaux","Cônes","Cordes","Bancs suédois (si disponibles)"],
      description:"Parcours avec différents types de sauts: sauter dans des cerceaux, par-dessus des cordes, sur un pied, en longueur.",
      etapes:["Installer le parcours (démo)","Passer en file indienne","3-4 passages par élève","Chronométrer pour se dépasser","Modifier le parcours"],
      variantes:["Sauts à cloche-pied","Sauts à deux pieds joints","Course + saut en longueur","Sauts en hauteur (cordes)"],
    },
    {
      id:"LOC_P2", categorie:"principal", nom:"⭐ Relais Junior",
      durees:[10,12,15], cycles:["1er cycle","2e cycle","3e cycle"],
      materiel:["Témoin (bâton/foulard) par équipe","Cônes de délimitation"],
      description:"Course de relais par équipes de 4-5. Plusieurs formules: aller-retour, en étoile, avec obstacles.",
      etapes:["Former des équipes de 4-5","Expliquer la transmission du témoin","Course aller-retour (3 manches)","Formule tournoi (chaque équipe contre chaque équipe)","Calcul des points"],
      variantes:["Relais à cloche-pied","Relais en marche arrière","Relais avec obstacles (slalom de cônes)","Transmission: balle au lieu de témoin"],
    },
    {
      id:"LOC_P3", categorie:"principal", nom:"⭐ Saut à la Corde",
      durees:[10,12,15], cycles:["1er cycle","2e cycle","3e cycle"],
      materiel:["1 corde par élève","2-3 longues cordes"],
      description:"Apprentissage progressif du saut à la corde: individuel, en entrée de corde tournée par 2 élèves.",
      etapes:["Saut individuel: 10 sauts consécutifs","Défis: sur 1 pied, double-sauts","Corde tournée: entrée + 5 sauts","Corde tournée: comptage collectif","Record de classe"],
      variantes:["Sauter en duo (même corde)","Double corde (deux cordes croisées)","Saut chorégraphié avec rythme musical"],
    },
    {
      id:"LOC_P4", categorie:"principal", nom:"⭐ Haies Adaptées",
      durees:[10,12,15], cycles:["2e cycle","3e cycle"],
      materiel:["Haies mousse ou cordes tendues entre cônes","Chronomètre"],
      description:"Course avec franchissement de haies adaptées. Apprentissage de la technique de passage.",
      etapes:["Marcher en enjambant les haies","Courir en enjambant","Technique: jambe d'attaque et jambe de traîne","Chronométrer 40m haies","Compétition par équipes"],
      variantes:["Haies à différentes hauteurs","Slalom entre les haies","Haies + sprint final"],
    },
    {
      id:"LOC_J1", categorie:"jeu", nom:"🎮 La Grande Chasse (Tag)",
      durees:[8,10,12], cycles:["Préscolaire","1er cycle","2e cycle"],
      materiel:["Foulards (1 par taggueur)","Cônes de délimitation"],
      description:"Jeux de poursuite variés. 2-3 taggueurs avec un foulard essaient de toucher tous les autres.",
      etapes:["Définir le terrain","Choisir 2-3 taggueurs","Jeu 3 min","Rotation des taggueurs","Variante pour finir"],
      variantes:["Freeze tag (figés jusqu'à être libérés)","Tag coloré (touche le t-shirt de la même couleur)","Tag chaîne (tagués rejoignent la chaîne)","Tag balles de neige (lancer un foulard)"],
    },
    {
      id:"LOC_J2", categorie:"jeu", nom:"🎮 Le Territoire",
      durees:[12,15,18], cycles:["1er cycle","2e cycle","3e cycle"],
      materiel:["Cônes (40+)","Dossards 2-4 couleurs"],
      description:"Chaque équipe essaie de ramasser le plus de cônes dans le camp adverse et de les rapporter dans son camp.",
      etapes:["Répartir les cônes également (20 chaque côté)","2 équipes de chaque côté","Ramasser et rapporter un cône à la fois","Si touché en zone adverse: retour à son camp","Équipe avec le plus de cônes gagne"],
      variantes:["3-4 équipes (chacun pour soi)","Zones de protection","Limite de temps (3 min)"],
    },
    {
      id:"LOC_R1", categorie:"retour", nom:"🧘 Étirements des Jambes",
      durees:[4,5,6], cycles:["Préscolaire","1er cycle","2e cycle","3e cycle"],
      materiel:[],
      description:"Étirements doux des principaux groupes musculaires des membres inférieurs utilisés lors de la course et des sauts.",
      etapes:["Quadriceps: tirer le pied derrière (20s chaque jambe)","Ischio-jambiers: jambe tendue, pencher (20s)","Mollets: appui contre le mur (20s chaque)","Adducteurs: papillon assis (20s)","Respirations profondes finales"],
      variantes:["Guidé par un élève","En musique douce","En position assise si sol propre"],
    },
    {
      id:"LOC_R2", categorie:"retour", nom:"🧘 Journal de Bord Moteur",
      durees:[5,7], cycles:["2e cycle","3e cycle"],
      materiel:["Cahier ou fiche par élève","Crayon"],
      description:"Les élèves notent dans leur journal: performance du jour, ressenti, défi pour la prochaine fois.",
      etapes:["Distribuer les journaux","Temps d'écriture (3 min)","Partage volontaire (2 min)","Fixer un objectif personnel pour la prochaine séance"],
      variantes:["Dessin de la séance (préscolaire/1er cycle)","Dictée à l'adulte","Formulaire pré-rempli"],
    },
  ],

  stabilisation: [
    {
      id:"STA_E1", categorie:"echauffement", nom:"🔥 Yoga des Animaux",
      durees:[5,7,8], cycles:["Préscolaire","1er cycle"],
      materiel:["Tapis optionnels"],
      description:"Échauffement en postures d'animaux: chien, chat, cobra, grenouille, arbre. L'enseignant nomme l'animal et les élèves imitent.",
      etapes:["Le chat (dos rond/creux)","Le chien tête en bas (triangle)","Le cobra (sur le ventre, dos cambré)","La grenouille (accroupi, genoux écartés)","L'arbre (équilibre sur un pied)","Le crocodile (planche)"],
      variantes:["Laisser les élèves inventer leurs propres animaux","Transition fluide entre les poses","Avec musique de nature"],
    },
    {
      id:"STA_P1", categorie:"principal", nom:"⭐ Parcours d'Équilibre",
      durees:[10,12,15], cycles:["Préscolaire","1er cycle","2e cycle"],
      materiel:["Poutres basses","Cerceaux","Lignes au sol","Coussins d'équilibre (si disponibles)"],
      description:"Parcours avec différents défis d'équilibre: marcher sur une ligne, sur poutre, sur un pied, sur surface instable.",
      etapes:["Marcher sur une ligne collée au sol","Marcher sur une poutre basse (bras en croix)","Équilibre sur un pied 5s","Sautiller de cerceaux en cerceaux","Combinaison finale"],
      variantes:["Yeux fermés sur ligne","Porter un objet sur la tête","Passage en tandem (main dans la main)"],
    },
    {
      id:"STA_P2", categorie:"principal", nom:"⭐ Roulades et Rotations",
      durees:[12,15,18], cycles:["1er cycle","2e cycle","3e cycle"],
      materiel:["Tapis de gym (1 par élève)","Repères visuels"],
      description:"Apprentissage progressif des roulades avant et arrière sur tapis. L'enseignant supervise individuellement.",
      etapes:["Position de départ (accroupi, menton poitrine)","Roulade avant guidée par l'enseignant","Roulade avant autonome (5 répétitions)","Roulade arrière (progression)","Enchaîner avant + arrière"],
      variantes:["Roulade de côté","Roulade avec objet dans les mains","Roulade + position finale imposée"],
    },
    {
      id:"STA_P3", categorie:"principal", nom:"⭐ Pyramides Humaines",
      durees:[15,18,20], cycles:["2e cycle","3e cycle"],
      materiel:["Tapis de gym","Fiches de pyramides illustrées"],
      description:"Construction de pyramides à 2, 3, puis 4 personnes. Travail de confiance, de force et de communication.",
      etapes:["Pyramides à 2 (10 min): 5 modèles illustrés","Pyramides à 3 (8 min): 3 modèles","Présentation des pyramides créées","Sécurité: un observateur par groupe"],
      variantes:["Pyramides thématiques (animaux, lettres)","Créer sa propre pyramide","Passage fluide entre 2 pyramides"],
    },
    {
      id:"STA_J1", categorie:"jeu", nom:"🎮 La Statue",
      durees:[8,10], cycles:["Préscolaire","1er cycle"],
      materiel:["Musique"],
      description:"Quand la musique joue, les élèves dansent. Quand elle s'arrête, ils restent figés dans leur position (statue). Dernier à bouger gagne.",
      etapes:["Musique joue: bouger librement","Musique s'arrête: statue immédiatement","L'enseignant observe qui bouge","Élimination douce","Varier les positions imposées (statue d'athlète, animal, etc.)"],
      variantes:["Statue d'équilibre imposée","Statue en paire (se tenir)","Le gagnant choisit la prochaine statue"],
    },
    {
      id:"STA_R1", categorie:"retour", nom:"🧘 Séquence de Yoga",
      durees:[5,7,8], cycles:["Préscolaire","1er cycle","2e cycle","3e cycle"],
      materiel:["Tapis (optionnel)","Musique douce"],
      description:"Séquence de postures de yoga adaptée pour revenir au calme: respiration, poses douces, relaxation finale.",
      etapes:["Respiration abdominale (3 cycles)","Enfant (child's pose, 20s)","Chien tête en bas (20s)","Guerrier 1 (20s chaque côté)","Savasana (allongé, 1 min)"],
      variantes:["Guidé par un élève","Avec visualisation guidée","Postures nommées en anglais ou dans une autre langue"],
    },
  ],

  cooperation: [
    {
      id:"COOP_E1", categorie:"echauffement", nom:"🔥 Le Nœud Humain",
      durees:[5,7], cycles:["1er cycle","2e cycle","3e cycle"],
      materiel:[],
      description:"Groupe de 8-10 élèves en cercle, mains entrelacées au centre, doivent se démêler sans lâcher les mains.",
      etapes:["Former un cercle de 8-10","Tendre la main droite vers quelqu'un non-adjacent","Tendre la main gauche vers quelqu'un d'autre","Se démêler sans lâcher","Objectif: former un cercle (ou 2 cercles liés)"],
      variantes:["Avec un défi de silence","Temps limite","Deux groupes en compétition"],
    },
    {
      id:"COOP_P1", categorie:"principal", nom:"⭐ La Rivière Coopérative",
      durees:[12,15,18], cycles:["1er cycle","2e cycle","3e cycle"],
      materiel:["Cerceaux (1 de moins que d'élèves)","Délimitation de la rivière"],
      description:"Toute la classe doit traverser la rivière en utilisant des cerceaux comme îlots. Si un pied touche l'eau, tout le groupe recommence.",
      etapes:["Définir la rivière (6-8m)","Distribuer N-1 cerceaux","L'équipe doit traverser en utilisant les cerceaux","Personne ne peut rester seul sur un îlot","Stratégie collective obligatoire"],
      variantes:["Retirer des cerceaux (plus difficile)","Ajouter un objet à transporter","Traversée les yeux fermés pour 1 membre"],
    },
    {
      id:"COOP_P2", categorie:"principal", nom:"⭐ Construction d'Équipe",
      durees:[15,18,20], cycles:["2e cycle","3e cycle"],
      materiel:["Défis écrits sur fiches","Matériaux variés selon le défi"],
      description:"Les équipes reçoivent un défi physique coopératif à résoudre: transporter un objet sur une toile, traverser un espace en équipe, etc.",
      etapes:["Former des équipes de 4-6","Distribuer le défi (lire et comprendre)","Temps de planification (3 min)","Réalisation (10 min)","Débriefing: comment avez-vous réussi?"],
      variantes:["Défi 1: ballon transporté sur toile sans les mains","Défi 2: toute l'équipe sur une feuille (rétrécissant)","Défi 3: traverser sans toucher le sol (cerceaux)"],
    },
    {
      id:"COOP_J1", categorie:"jeu", nom:"🎮 Ballon Coopératif",
      durees:[10,12,15], cycles:["Préscolaire","1er cycle","2e cycle"],
      materiel:["1 ballon gonflable léger","Délimitation du terrain"],
      description:"Toute la classe coopère pour empêcher le ballon de tomber au sol. Défi collectif: battre le record de passes.",
      etapes:["Former un grand cercle","Frapper le ballon vers le haut (une touche à la fois)","Compter les touches consécutives","Objectif: atteindre 20, 30, 50 touches","Défi: chaque élève doit toucher avant de répéter"],
      variantes:["Deux ballons simultanément","Zone interdite (pas 2× de suite)","Ballon de plage vs ballon mousse (vitesse différente)"],
    },
    {
      id:"COOP_R1", categorie:"retour", nom:"🧘 Massage en Chaîne",
      durees:[4,5], cycles:["2e cycle","3e cycle"],
      materiel:[],
      description:"En file indienne, chaque élève masse doucement les épaules de la personne devant lui. Puis tout le monde se retourne.",
      etapes:["Former une longue file","Mains sur les épaules de la personne devant","Massage doux des épaules (1 min)","Tout le monde se retourne","Massage dans l'autre sens"],
      variantes:["Massage du dos (poings légers)","Ajouter de la musique douce","Consentement explicite avant de commencer"],
    },
  ],

  opposition: [
    {
      id:"OPP_E1", categorie:"echauffement", nom:"🔥 Défis de Réaction",
      durees:[5,7,8], cycles:["1er cycle","2e cycle","3e cycle"],
      materiel:["Cônes de couleurs","Foulards"],
      description:"En paires, un signal déclenche une réaction: attraper le foulard posé entre les deux avant l'adversaire.",
      etapes:["En paires face à face (1m)","Foulard au sol entre les deux","Signal (clap, son): attraper le foulard","Tally des points","Varier les signaux (couleur, geste)"],
      variantes:["Toucher un cône désigné","Réaction à un mot dans une liste","À 3 (1 contre 2)"],
    },
    {
      id:"OPP_P1", categorie:"principal", nom:"⭐ Ballon Chasseur Pédagogique",
      durees:[15,18,20], cycles:["1er cycle","2e cycle","3e cycle"],
      materiel:["4-6 ballons de mousse","Cônes","Dossards 2 couleurs"],
      description:"Apprentissage progressif du ballon chasseur avec accent sur les stratégies offensives et défensives.",
      etapes:["Règles de base (5 min)","Jeu libre (5 min)","Pause stratégique: que faisons-nous bien/mal?","Jeu avec stratégie (5 min)","Évaluation collective"],
      variantes:["Version prison","Version médicale","Version 3 équipes en triangle","Version avec zones de tir obligatoires"],
    },
    {
      id:"OPP_P2", categorie:"principal", nom:"⭐ Mini-Tournoi d'Opposition",
      durees:[15,18,20], cycles:["2e cycle","3e cycle"],
      materiel:["Terrain délimité","Dossards","Feuille de résultats"],
      description:"Tournoi d'opposition rapide (jeux à 5 points). Chaque équipe joue contre chaque équipe. Tableau des résultats affiché.",
      etapes:["Former 4 équipes de 4-5","5 min par partie (jusqu'à 5 points)","Rotation: chaque équipe joue vs toutes les autres","Calculer les points totaux","Cérémonie simple (applaudissements)"],
      variantes:["Ballon chasseur","Tag-foulard","Défi de précision","Jeu de leur choix (vote)"],
    },
    {
      id:"OPP_J1", categorie:"jeu", nom:"🎮 Tag Stratégique",
      durees:[10,12,15], cycles:["1er cycle","2e cycle","3e cycle"],
      materiel:["Foulards de couleurs (1 par élève)","Cônes"],
      description:"Chaque élève a un foulard dans son dos. Objectif: attraper les foulards des autres sans perdre le sien.",
      etapes:["Distribuer 1 foulard par élève (dans le dos du pantalon)","Attraper les foulards des autres","Celui qui perd son foulard continue (compter ses captures)","Fin: compter les foulards capturés","Discussion: quelle stratégie a fonctionné?"],
      variantes:["En équipes (protéger les coéquipiers)","Zone de sécurité (30 secondes max)","Foulard dans le dos + une main attachée (défi)"],
    },
    {
      id:"OPP_R1", categorie:"retour", nom:"🧘 Analyse Tactique",
      durees:[5,7], cycles:["2e cycle","3e cycle"],
      materiel:["Tableau ou papier grand format","Marqueur"],
      description:"Retour sur les stratégies utilisées: dessiner le terrain, montrer les stratégies efficaces et celles à améliorer.",
      etapes:["Dessiner le terrain au tableau","Demander: quelle stratégie avez-vous utilisée?","Identifier ce qui a fonctionné","Identifier ce à améliorer","Proposer une nouvelle stratégie pour la prochaine fois"],
      variantes:["Les élèves dessinent eux-mêmes","Discussion en équipes avant partage général","Écrire 1 chose apprise"],
    },
  ],

  expression: [
    {
      id:"EXP_E1", categorie:"echauffement", nom:"🔥 Miroir en Mouvement",
      durees:[5,7,8], cycles:["Préscolaire","1er cycle","2e cycle","3e cycle"],
      materiel:[],
      description:"En paires, un élève fait des mouvements lents que l'autre imite comme un miroir. Échange des rôles.",
      etapes:["En paires face à face","Leader fait des mouvements très lents","Miroir suit simultanément","Changer de leader après 2 min","Difficile: les deux ensemble, sans leader désigné"],
      variantes:["Avec musique slow","En groupe de 4 (2 miroirs)","Mouvements thématiques (nature, sport, travail)"],
    },
    {
      id:"EXP_P1", categorie:"principal", nom:"⭐ Création Chorégraphique",
      durees:[15,18,20], cycles:["2e cycle","3e cycle"],
      materiel:["Musique variée","Lecteur audio"],
      description:"Les élèves créent en groupes une chorégraphie de 16 temps sur une musique choisie. Contraintes créatives imposées.",
      etapes:["Former des groupes de 4-5","Écouter la musique (1 min)","Créer 8 mouvements au minimum","Répétition (5 min)","Présentation au groupe (30s par équipe)"],
      variantes:["Thème imposé (animaux, sports, nature)","Contrainte: niveau au sol obligatoire","Contrainte: formation symétrique","Contrainte: 1 élément acrobatique"],
    },
    {
      id:"EXP_P2", categorie:"principal", nom:"⭐ Danse Culturelle du Monde",
      durees:[15,18,20], cycles:["1er cycle","2e cycle","3e cycle"],
      materiel:["Musique authentique du pays","Foulards optionnels"],
      description:"Apprentissage d'éléments d'une danse d'une culture du monde: haka (Nouvelle-Zélande), samba (Brésil), tinikling (Philippines), etc.",
      etapes:["Présentation culturelle (2 min, images si possible)","Apprentissage progressif des pas (8 min)","Pratique en groupe (5 min)","Danse complète","Discussion: que retiens-tu de cette culture?"],
      variantes:["Haka (Nouvelle-Zélande)","Samba (Brésil)","Tinikling aux bâtons (Philippines)","Danse autochtone québécoise","Capoeira de base (Brésil)"],
    },
    {
      id:"EXP_J1", categorie:"jeu", nom:"🎮 Freeze Danse Expressif",
      durees:[8,10], cycles:["Préscolaire","1er cycle"],
      materiel:["Musique variée (différents styles)"],
      description:"Les élèves dansent sur la musique et doivent s'arrêter dans une pose expressive quand elle s'arrête. L'enseignant commente les poses créatives.",
      etapes:["Musique joue: danse libre","Musique stop: pose expressive immédiate","L'enseignant nomme 2-3 poses originales","Recommencer avec musique différente","Thème: 'Cette fois, bougez comme si vous étiez sous l'eau'"],
      variantes:["Thèmes: bonheur, tristesse, surprise, colère (émotions)","Bougez comme un robot","Bougez en slow-motion","Bougez comme votre animal préféré"],
    },
    {
      id:"EXP_R1", categorie:"retour", nom:"🧘 Relaxation Guidée",
      durees:[5,7,8], cycles:["Préscolaire","1er cycle","2e cycle","3e cycle"],
      materiel:["Tapis","Musique douce ou nature"],
      description:"Allongés sur le dos, les élèves suivent une courte relaxation guidée par la voix de l'enseignant. Images positives et respiration.",
      etapes:["S'allonger sur le dos","Fermer les yeux","Respiration: inspire 4 temps, expire 4 temps","Visualisation: 'Tu es sur une plage calme...'","Retour progressif: bouger les doigts, les orteils, s'étirer"],
      variantes:["En position assise (si pas de tapis)","Guidé par un élève","Thèmes: forêt, plage, montagne, espace"],
    },
  ],

  manipulation_engins: [
    {
      id:"MEG_E1", categorie:"echauffement", nom:"🔥 Maîtrise de la Raquette",
      durees:[5,7], cycles:["1er cycle","2e cycle","3e cycle"],
      materiel:["1 raquette par élève","1 volant/balle par élève"],
      description:"Exercices de prise en main et contrôle de la raquette: équilibre du volant, frappes douces en l'air.",
      etapes:["Tenir la raquette correctement (démo)","Équilibrer le volant sur la raquette (30s)","Frapper doucement vers le haut (10 fois)","Marcher en équilibrant le volant","Jongler: alterner raquette avant/arrière"],
      variantes:["Raquette non-dominante","Yeux fermés (équilibrer)","Compétition amicale de jonglage"],
    },
    {
      id:"MEG_P1", categorie:"principal", nom:"⭐ Échanges Progressifs",
      durees:[10,12,15], cycles:["1er cycle","2e cycle","3e cycle"],
      materiel:["1 raquette par élève","1 volant/balle pour 2"],
      description:"En paires, progression des échanges: filet imaginaire, filet réel. Distance et complexité augmentent.",
      etapes:["À 2m: frapper vers le haut (10 échanges)","À 3m: échanges directs","Introduire un filet ou une ligne","10 échanges consécutifs comme défi","Tournoi amical (5 points)"],
      variantes:["Coup droit seulement","Alterner coup droit / revers","Placement (viser les côtés du terrain)"],
    },
    {
      id:"MEG_P2", categorie:"principal", nom:"⭐ Hockey Doux",
      durees:[12,15,18], cycles:["1er cycle","2e cycle","3e cycle"],
      materiel:["Bâtons de hockey mousse","Balles ou rondelles légères","Buts","Dossards"],
      description:"Apprentissage du hockey adapté: contrôle de la rondelle, passes, jeu avec filets. En équipes de 3-4.",
      etapes:["Contrôle de la rondelle (3 min)","Passes en paires (3 min)","Mini-jeu 3v3 (5 min)","Rotation des équipes","Tournoi final"],
      variantes:["Sans gardien (but ouvert)","Obligation de 3 passes avant de tirer","Hockey assis (accessibilité)"],
    },
    {
      id:"MEG_R1", categorie:"retour", nom:"🧘 Étirements des Avant-Bras",
      durees:[4,5], cycles:["1er cycle","2e cycle","3e cycle"],
      materiel:[],
      description:"Étirements ciblés sur les muscles sollicités par la manipulation d'engins: avant-bras, poignets, épaules.",
      etapes:["Tendre le bras, plier le poignet vers le bas (20s)","Plier le poignet vers le haut (20s)","Rotation complète des poignets (10×)","Étirement de l'épaule (croiser le bras)","Respiration finale"],
      variantes:["Guidé par un élève","Ajouter l'étirement du cou","Massage des avant-bras"],
    },
  ],

  plein_air: [
    {
      id:"PA_E1", categorie:"echauffement", nom:"🔥 Marche Active en Nature",
      durees:[5,8,10], cycles:["1er cycle","2e cycle","3e cycle"],
      materiel:["Terrain extérieur"],
      description:"Marche rapide dans la cour en observant la nature. L'enseignant pose des défis d'observation.",
      etapes:["Marche normale (2 min)","Marche rapide avec bras actifs (2 min)","Arrêts d'observation (1 min): trouver 3 choses vertes","Course légère (1 min)","Retour à la marche"],
      variantes:["Course d'orientation simple (trouver des balises)","Marche en silence (écouter la nature)","Marche avec défis d'équilibre naturels (branches, roches)"],
    },
    {
      id:"PA_P1", categorie:"principal", nom:"⭐ Initiation à l'Orientation",
      durees:[15,18,20], cycles:["2e cycle","3e cycle"],
      materiel:["Carte simple de la cour","Boussoles","Balises numérotées"],
      description:"Trouver des balises cachées dans la cour à l'aide d'une carte et d'une boussole simplifiée.",
      etapes:["Présentation de la carte et boussole (5 min)","Trouver les points cardinaux sur le terrain","Chercher 5 balises en équipe de 2","Récupérer le code de chaque balise","Équipe avec tous les codes gagne"],
      variantes:["Balises avec défis sportifs","Avec QR codes sur balises","Course d'orientation chronométrée"],
    },
    {
      id:"PA_J1", categorie:"jeu", nom:"🎮 Jeux Traditionnels Extérieurs",
      durees:[12,15,18], cycles:["1er cycle","2e cycle","3e cycle"],
      materiel:["Craie pour tracer","Matériaux naturels"],
      description:"Jeux de cour traditionnels québécois et du monde: marelle, élastique, tague, billes adaptées.",
      etapes:["Choisir 2-3 jeux avec vote","Tracer les zones si nécessaire","Jeu par rotation (5 min chacun)","Discussion: d'où viennent ces jeux?","Créer une variante"],
      variantes:["Marelle québécoise","Élastique (comptines)","Poison (tag avancé)","Jeu autochtone: lancé de mocassin adapté"],
    },
    {
      id:"PA_R1", categorie:"retour", nom:"🧘 Cercle de la Nature",
      durees:[5,7], cycles:["1er cycle","2e cycle","3e cycle"],
      materiel:["Terrain naturel"],
      description:"Assis en cercle dans la nature, les élèves partagent une observation naturelle et font des respirations profondes en plein air.",
      etapes:["S'asseoir en cercle sur l'herbe ou pavement","Chacun partage 1 chose observée dans la nature","3 respirations profondes ensemble","Qu'as-tu aimé aujourd'hui en plein air?","Ramasser tout déchet visible (responsabilité)"],
      variantes:["Écrire une observation dans le journal","Dessiner rapidement la nature observée","Méditation courte en plein air"],
    },
  ],
};

const DUREES_PERIODE = [30, 35, 40, 45, 50, 55, 60, 75, 90];
const NB_PERIODES = [1,2,3,4,5,6,7,8,9,10,12,15,20];

const TEMPS_PAR_CATEGORIE = {
  echauffement: { min: 5, max: 15, pct: 0.20 },
  principal:    { min: 15, max: 45, pct: 0.65 },
  jeu:          { min: 8, max: 25, pct: 0.0  },
  retour:       { min: 3, max: 10, pct: 0.15 },
};

if (typeof module !== 'undefined') module.exports = { MOYENS_ACTION, OBJECTIFS_PFEQ, EDUCATIFS, DUREES_PERIODE, NB_PERIODES };
